export const contentData = {
  companiesData: [
    {
      uid: '0',
      cvrNumber: '12345678',
      companyName: 'Zervant',
      address: 'Keilaranta 17C',
      postNoCity: 'FI-02150 ESPOO',
      companyType: 'Limited company',
      status: 'Active',
    },
    {
      uid: '1',
      cvrNumber: '12345678',
      companyName: 'Kontist',
      address: 'Kastanienallee 98B',
      postNoCity: '10435 Berlin',
      companyType: 'GmbH',
      status: 'Active',
    },
    {
      uid: '2',
      cvrNumber: '12345678',
      companyName: 'Billy',
      address: 'Vesterbrogade 1C, 6.',
      postNoCity: '1620 København V',
      companyType: 'Limited Liability Company',
      status: 'Active',
    },
    {
      uid: '3',
      cvrNumber: '12345678',
      companyName: 'Tellow',
      address: ' Danzigerkade 207',
      postNoCity: '1013 AP Amsterdam',
      companyType: '	Limited company',
      status: 'Active',
    },
    {
      uid: '4',
      cvrNumber: '12345678',
      companyName: 'Salary',
      address: 'Vesterbrogade 1E, 6.',
      postNoCity: '1620 København V',
      companyType: 'Limited Liability Company',
      status: 'Active',
    },

    {
      uid: '5',
      cvrNumber: '12345678',
      companyName: 'Ageras Finance',
      address: 'Ahnqwstråde 6, st.',
      postNoCity: '2500 Valby',
      companyType: 'Limited Liability Company',
      status: 'Active',
    },
  ],
}
